import os
import argparse
import requests
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# --- Configuration ---
SCOPES = [
    'https://www.googleapis.com/auth/presentations.readonly',
    'https://www.googleapis.com/auth/drive.readonly'
]

# --- Google API Authentication ---
def get_api_service(credentials_path):
    """Authenticates with Google APIs using a service account and returns a service object."""
    if not os.path.exists(credentials_path):
        print(f"ERROR: Credentials file not found at '{credentials_path}'.")
        return None
    try:
        creds = service_account.Credentials.from_service_account_file(
            credentials_path, scopes=SCOPES
        )
        print("Authentication successful using service account.")
        return build('slides', 'v1', credentials=creds)
    except Exception as e:
        print(f"Error during authentication: {e}")
        return None

# --- Core Conversion Logic (Updated) ---
def convert_presentation(service, presentation_id, original_path):
    """Fetches each slide of a presentation and saves it as a high-quality PNG."""
    try:
        print(f"\nFetching presentation with ID: {presentation_id}")
        presentation = service.presentations().get(presentationId=presentation_id).execute()
        slides = presentation.get('slides', [])
        
        if not slides:
            print("Warning: The presentation has no slides.")
            return

        print(f"Found {len(slides)} slides. Starting conversion...")
        
        base_output_dir = os.path.dirname(original_path)

        for i, slide in enumerate(slides):
            page_id = slide['objectId']
            slide_number = i + 1
            
            # --- CHANGE 1: Create the folder if it doesn't exist ---
            output_folder = os.path.join(base_output_dir, f"Slide {slide_number}")
            os.makedirs(output_folder, exist_ok=True) # This safely creates the directory
            
            output_filepath = os.path.join(output_folder, f"Slide {slide_number}.png")
            
            # --- CHANGE 2: Request a LARGE thumbnail for better quality ---
            thumbnail_request = service.presentations().pages().getThumbnail(
                presentationId=presentation_id,
                pageObjectId=page_id,
                thumbnailProperties_thumbnailSize='LARGE' # Request high-resolution image
            )
            thumbnail_url = thumbnail_request.execute()['contentUrl']

            # Download and save the image
            response = requests.get(thumbnail_url)
            if response.status_code == 200:
                with open(output_filepath, 'wb') as f:
                    f.write(response.content)
                print(f"  -> Successfully saved {output_filepath}")
            else:
                print(f"  -> FAILED to download slide {slide_number}. Status: {response.status_code}")

    except HttpError as error:
        print(f"An API error occurred: {error}")

# --- Main Execution ---
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Converts the first valid presentation from an input file into PNG slides.')
    parser.add_argument("input_file", help="The .out file generated by find_files_by_type.py.")
    parser.add_argument("-c", "--credentials", required=True, help="Path to your service account credentials JSON file.")
    args = parser.parse_args()

    if not os.path.exists(args.input_file):
        print(f"Error: Input file not found at '{args.input_file}'")
        exit()

    service = get_api_service(args.credentials)
    if not service:
        exit()

    target_id = None
    target_path = None
    with open(args.input_file, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            if i == 0: continue

            parts = line.strip().split('\t')
            if len(parts) == 2 and parts[0] != "NOT_FOUND":
                target_id = parts[0]
                target_path = parts[1]
                break

    if target_id and target_path:
        convert_presentation(service, target_id, target_path)
    else:
        print("No valid presentation ID found in the input file.")